export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';
// export const FECTCH_POSTS_RESET = 'USER_DETAILS_RESET';

export const POST_COMMENT_CREATE_REQUEST = 'POST_COMMENT_CREATE_REQUEST';
export const POST_COMMENT_CREATE_SUCCESS = 'POST_COMMENT_CREATE_SUCCESS';
export const POST_COMMENT_CREATE_FAIL = 'POST_COMMENT_CREATE_FAIL';
export const POST_COMMENT_CREATE_RESET = 'POST_COMMENT_CREATE_RESET';

export const EDIT_POST_REQUEST = 'EDIT_POST_REQUEST';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
export const EDIT_POST_FAIL = 'EDIT_POST_FAIL';